name: CI

on:
  push:
   branches:
     - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Fetch full history
      run: git fetch --prune --tags --unshallow

    - name: Compute Short SHA
      id: sha_short
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Setup YQ
      uses: chrisdickinson/setup-yq@latest

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASS }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
       push: true
       tags: armory/spud-stories:sha-${{ steps.sha_short.outputs.sha_short }}

    - uses: Azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.DEV_KUBECONFIG }}

    - name: Deploy to Dev
      uses: Azure/k8s-deploy@v1.4
      with:
        namespace: 'ethan-dev'
        images: 'armory/spud-stories:sha-${{ steps.sha_short.outputs.sha_short }}'
        manifests: |
            deployment.yaml
            service.yaml
        strategy: blue-green
        route-method: service # should be the same as the value when action was deploy